params:
  color: green  # Any color in CSS syntax
  width: 85rem  # Any length in CSS syntax
  footer: <a href="http://www.wtfpl.net/about/" target=_blank><img src="/wtfpl-badge-4.png"> </a>
menu:
  nav:
  - name: About
    url: about/
    weight: 1
  - name: Posts
    url: post/
    weight: 2
  - name: Pentest Resources
    url: pentest-resources/
    weight: 3
